# Generated by Django 4.0.3 on 2022-04-12 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant_api', '0002_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant_api.plant'),
        ),
    ]
