# Generated by Django 4.0.3 on 2022-04-13 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_api', '0003_alter_status_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='plant',
        ),
    ]
