# Generated by Django 4.0.3 on 2022-04-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('image', models.CharField(max_length=32)),
                ('pot_size', models.PositiveIntegerField()),
                ('room_name', models.CharField(max_length=32)),
                ('direction', models.CharField(max_length=2)),
                ('user_notes', models.CharField(max_length=100)),
            ],
        ),
    ]
