# Generated by Django 4.0.3 on 2022-04-14 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant_api', '0003_alter_status_plant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='user_notes',
            new_name='notes',
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('schedule', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant_api.plant')),
            ],
        ),
    ]
