# Generated by Django 4.0.3 on 2022-04-14 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_api', '0004_rename_user_notes_plant_notes_alter_plant_image_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='room_name',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='pot_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='due',
        ),
    ]
