# Generated by Django 4.0.3 on 2022-04-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_api', '0007_alter_plant_image_alter_plant_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='task',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='created',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
